# Mass Transfer {#sec-mass}
Mass transfer occurs through similar processes as heat transfer.
In fact the mathematics of mass transfer is often based on a formal analogy with heat transfer. 
Mass transfer is simpler in some ways--in particular there is only mass, unlike heat where we have temperature and energy to think about.
But in other ways it is more complicated, especially for systems with multiple phases.
Here we'll cover advection, diffusion, and convection.

## Advection
As with heat transfer, advection describes bulk flow.
Here is a simple equation for mass flow of some solute or component present in a flowing fluid:

$$
\dot{m} = c \cdot \dot{V},
$${#eq-mass_advect_1}

where $\dot{m} =$ mass flow rate of some component ($\kgps$), $c =$ volumetric concentration of component ($\kgpmc$), and $\dot{V} =$ volumetric fluid flow rate ($\mcbps$).
Assuming we have flow in one direction in a pipe or some other system with a uniform cross-sectional area $A$, we can get flux by dividing by cross-sectional area,
$$
J = c \cdot v_x,
$${#eq-mass-advect-1}

where $\frac{\dot{V}}{A} = v_x =$ superficial fluid velocity.

For a fixed point in space, 

$$ 
\frac{dc}{dt} = v_x \cdot \frac{dc}{dx}.
$${#eq-mass-advect-ode1}

With mass, we don't have anything like the temperature vs. energy distinction.
Mass concentration gradients drive mass flow directly, altering concentrations over time.

<!-- Simple bulk flow. Include note on dispersion. -->

## Diffusion and Fick's laws {#sec-fick}

Diffusion is the term for mass transfer through random molecular or atomic movement.
Fick's law is:

$$ 
J = - D \cdot \frac{dc}{dx},
$${#eq-ficks1}

where $D$ is the diffusivity or diffusion coefficient ($\msqps$, but $\mathrm{cm^{2}~s^{-1}}$ is commonly used) and $c$ is concentration ($\kgpmc$).
The minus sign indicates that flow occurs down a concentration gradient, from high to low concentration.
It is possible to do a lot with just @eq-ficks1 using numerical modeling.
Like constitutive equations in general, Fick's law includes on the RHS a material property, $D$, and a state variable, $c$.

Diffusivity is properly called a *binary* diffusion coefficient, because it depends on both materials.
For example, values of $D$ for oxygen in air and water are of course different, but so are the values for air and ethanol both in air. 
Diffusivity values vary widely.
For diffusion in gases, values are around 0.1 $\mathrm{cm^{2}~s^{-1}}$, or $10^{-5} \msqps$.
In water, $D$ values are on the order of $10^{-9} \msqps$.

The time derivative of concentration is the integral of @eq-ficks1, or:
$$ 
\frac{dc}{dt} = - D \cdot \frac{d^2c}{dx^2}.
$${#eq-ficks2}
This form can be used as a starting point for a numerical or analytical solution.


<!-- Diffusivity D depends on both the diffusing species and the medium.
     Approximate ranges for gases, liquids, solids. -->

## Convection

## Mass transfer coefficient approach

## Interphase mass transfer {#sec-interphase}

<!-- Transfer through an interface between two phases.
     This section likely needs more depth than the others given the topic's importance. -->

## Linking equations

<!-- Generally not needed; mass is mass. -->

## Example: dissolved oxygen transport and consumption
