# Chemical reactions and microbiology {#sec-reactions}

Chemical reactions, including those carried out by microorganisms, are important in innumerable processes in both engineered and natural systems.
This chapter will scratch the surface, barely, of the topics.

## Stoichiometry

Chemical *stoichiometry* is about the coefficients that accompany the reactants and products in a balanced chemical reaction.
For example, the simple organic compound urea (a waste product in mammal urine) is hydrolyzed like this:

$$
\ce{CO(NH2)2 + H2O -> 2NH3 + CO2}
$${#eq-urea1}

So the stoichiometry shows that hydrolysis of one mole of urea consumes one mole of water and produces two moles of ammonia and one of carbon dioxide.
Why do we care?
Well, these stoichiometric coefficients can then be used directly in a model to get state variable derivatives from the reaction rate, which itself is calculated using the appropriate constitutive equation.
In the framework presented in @sec-formulation, the stoichiometric coefficients go into creating linking equations (see @sec-linking for a review, if needed).
We then just need a single constitutive equation for the *overall reaction rate* (we will get to that in @sec-rxn-rates below) and simple linking equations for each chemical species.
For example, if our reaction rate is $r$, with units of $\molpmcps$, then the derivative for $\ce{CO(NH2)2}$ would be

$$
\frac{dc_{urea}}{dt} = -1 \cdot r,
$$

for ammonia,

$$
\frac{dc_{\ce{NH3}}}{dt} = 2 \cdot r,
$$

and carbon dioxide,

$$
\frac{dc_{\ce{CO2}}}{dt} = 2 \cdot r,
$$

all with units of $\molpmcps$.
The coefficients in these ODEs come directly from @eq-urea1.
Simple!
When implemented in Python (or written down on paper as a mathematical model, for that matter) a coefficient array can be combined with a state variable array for compact and efficient code when there is more than one state variable, as implied in the above example.
We will see some of that later.

There are some complications that come from using other units.
In many cases, it is not moles but species mass, or even mass of a particular element that is of interest; then the coefficients need to be adjusted, and this can be done in at least these two ways:

1. hidden unit conversion: here the user only sees the input and output units, which should be identical, but internally the ODEs uses moles, and conversion is carried out in the model on inputs and output,
2. consistent units: here the core of the computer model uses the input and output units; one set of units everywhere.

Mistakes can be made with either approach!
An advantage of 1 is that the coefficients have integer and usually obvious values, so it is easy to check values.

## Reaction rates {#sec-rxn-rates}

The constitutive equation for a chemical reaction must quantify its *rate*, or how fast it proceeds, e.g., $\molps$, $\molpmcps$, or on a mass basis, e.g., $\gpmcps$.
The term *kinetics* is used to describe reaction rates.
Here we will look at only two simple, and to some degree, idealized, cases: first-order reactions and second-order reactions.

A reaction that follows first-order kinetics has a rate that is proportional to the quantity of reactant present.
So that means:

$$
r_m = \frac{dM}{dt} = - k \cdot M,
$${#eq-fom1}

for mass or

$$
r_c = \frac{dc}{dt} = - k \cdot c,
$${#eq-fom2}

for concentration.
The inclusion of the derivatives in @eq-fom1 and @eq-fom2 only makes sense if the reaction is the *only* process affecting the quantity of reactant, i.e., a batch system with no addition of non-reaction removal of reactant.
The $k$ is the first-order reaction rate constant with dimensions $\text{T}^{-1}$.
It is not necessarily constant, and depends at least on temperature for most chemical reactions.
But its value does not change as the reaction proceeds, at least not for a true first-order reaction.
A classic example of a first-order reaction is radioactive decay.
Many other chemical reactions are not truly first-order, but come close enough for modelling purposes.
Or, more honestly, an accurate description of the relevant kinetics is not available or too complicated, and a first-order model is assumed to be close enough! 
Even where the concentration of a reactant seems to follow first-order kinetics over time, the true rate often depends on other factors, e.g., the constant concentration of another reactant or competitor, or the solution pH, for example, 
These effects can be important when applying the model--the rate "constant" from one system may not apply directly to another.

Thinking about math and implementation, the rate of a simple first-order reaction can be described analytically with the exponential model (see @sec-expmodel). 
You could have (should have, really!) realized this just from the form of @eq-fom1 or @eq-fom2!
Compare @eq-fom2 to @eq-exp-ode.
What specific variables or parameters go in for the $x$ and $\lambda$ in @eq-exp-ode?
Well, $x = c$ and $\lambda = -k$.
Note the minus sign!
Now take a look at @eq-exp-solution and plug these in.
That gives:

$$
c = c_0 \cdot e^{-k \cdot t}.
$${#eq-fom-solution1}

Simple!

With this simple analytical model we can predict the concentration of our reactant (e.g., urea) at any time.
We could also predict the rate by combining @eq-fom-solution1 and @eq-exp-ode.

If a reaction includes two reactants it might be possible to approximate the observed rate with a *second-order* model, i.e., 

$$
r_c = \frac{dc}{dt} = - k \cdot c_1 \cdot c_2, 
$${#eq-som1}

where $c_1$ is the concentration of the first reactant and $c_2$ the second one.
While there are analytical solutions for some second-order reaction scenarios, we won't cover them (you can read more [here](https://chem.libretexts.org/Bookshelves/Physical_and_Theoretical_Chemistry_Textbook_Maps/Supplemental_Modules_(Physical_and_Theoretical_Chemistry)/Kinetics/02%3A_Reaction_Rates/2.08%3A_Second-Order_Reactions)).
But @eq-som1 can be dropped into a numerical model easily!

You can find some guidance on determining reaction rate constant values in @sec-parameter-values.

Here is a Python example. . . 

## Equilibrium reactions

Rapid reversible chemical reactions are often at *equilibrium*, meaning the concentrations of chemical species do not change over time.
Here we will look at one important type of equibrium reaction: acid-base or proton exchange.
For more on these types of problems, see @Snoeyink1980.

Acid-base reactions are important in natural and engineered systems for influencing pH, which affects many processes.
In both types of systems, a set of chemical species and reactions that are together called the *carbonate system* are an important system.
The carbonate system plays an important role in processes in the oceans, municipal wastewater, and your blood!
Several *chemical species* play a role:

* $\ce{CO2(g)}$ is a gas,
* $\ce{CO2(aq)}$ is a what you get when $\ce{CO2}$ dissolves in water--it is an uncharged solute surrounded by water molecules,
* $\ce{H2CO3}$ is called carbonic acid, and is formed when $\ce{CO2(aq)}$ reacts with water in a hydration reaction,
* $\ce{H2CO3*}$ is not actually a chemical species, but the sum of $\ce{CO2(aq)}$ and $\ce{H2CO3}$, used because it is difficult to measure the two separately,
* $\ce{HCO3-}$ is bicarbonate, and is the most important buffer component in some systems, and
* $\ce{CO32-}$ is carbonate.

Chemical speciation models are used to determine the concentration of specific chemical species.
A fundamental concept here is that the *mass action expression* or *reaction quotient* takes on a specific numeric value at equilibrium.
For example, let's look at a reaction between only two of the carbonate system species:

$$
\ce{H2CO3^* <=> HCO3- + H+}.
$${#eq-carb1}

The mass action expression or reaction quotient for any reaction is the (mathematical) product of (reaction) product concentrations divided by the product of reactant concentrations.
Each concentration should be raised to the power of the stoichiometric coefficient, which are all 1 in this reaction.
So for @eq-carb1, we have:

$$
\frac{c_{\ce{HCO3-}} \cdot c_{\ce{H+}}}{c_{\ce{H2CO3^*}}},
$${#eq-carb-rq1}

where $c=$ molar or molal concentration, i.e., moles of species per L of water or moles per kg of water.
At equilibrium, the numeric value of that reaction quotient, @eq-carb-rq1, is know: at 15$\degC$ it is $3.80 \cdot 10^{-7}$ (@Snoeyink1980: p. 157).
Actually, except for very dilute solutions, for accurate results a correction is needed for interactions between ions, but the use of concentrations can still give decent approximate values. 
See @Snoeyink1980 for more information on chemical activity and ionic strength.
But typically, because the value of constants vary by orders of magnitude, these constants are expressed as the negative logarithm (base 10) and we'll see $pK_a$.
So here, $pK_a = 6.42$.
The numeric value is called the *equilibrium constant*

So, if we know the concentration of $\ce{H2CO3^*}$ and $\ce{H^+}$ we can calculate the concentration of bicarbonate $\ce{HCO3-}$ using the equilibrium constant.
The hydrogen ion (or "proton", because that it what it is) concentration is commonly take from pH, i.e.,

$$
p\text{H} = - log_{10}(c_{H^+}).
$${#eq-pH-def}

Even better, if we could use other, independent, information, we can solve for all species concentrations, including $\ce{H+}$, which means we could calculate pH. 
We can use element balance (commonly H balance) or charge balance for that other information.
The programming might be a bit much for this course, so we will include an example in an appendix . . .

## Ammonia equilibrium

Here is a simple example for ammonia.
This is another thing all environmental engineers should know!

The relevant proton exchange (acid-base) reaction is:

$$
\ce{NH4+ <=> NH3 + H+},
$${#eq-amm-dis}

with an equilbrium constant $k_a$, where the $a$ is for acid dissociation constant.
The numeric value is around $pk_a = 9.56$ at 15 $\degC$ (@clegg_chemical-model_1995). 

Let's write the mass action expression and set it to the acid dissociation constant:

$$
k_a = \frac{c_{\ce{NH3(aq)}} \cdot c_{\ce{H+}}} {c_{\ce{NH4+}}}.
$${#eq-amm-mae1}

What else can we use?
Well, we cannot measure the ammonium ($\ce{NH4+}$) concentration directly.
But it is trivial to measure the sum of $\ce{NH4+}$ and $\ce{NH3}$ as N mass, which is often called TAN (for total ammoniacal nitrogen) concentration in agriculture and related fields.
And then from mass conservation, we know that:

$$
c_{\text{TAN}} = c_{\ce{NH4+}} + c_{\ce{NH3}(aq)}.
$${#eq-amm-mass-bal}

Lastly, we can estimate $\ce{H+}$ from measured pH, or anyway use it as an input here.
That's all we need.
To get an explicit closed-form solution, we can rearrange @eq-amm-mass-bal to solve for $\ce{NH4+}$, and insert the result into @eq-amm-mae1, and finally rearrange to solve for $\ce{NH3(aq)}$.
We'll show these steps below, in part because the ability to do these kinds of simple mathematical derivations seems to be declining among students!

First, rearrange @eq-amm-mass-bal to solve for $\ce{NH4+}$:

$$
c_{\ce{NH4+}} = c_{\text{TAN}} - c_{\ce{NH3}(aq)}.
$${#eq-amm-der1}

And insert this into @eq-amm-mae1:

$$
k_a = \frac{c_{\ce{NH3(aq)}} \cdot c_{\ce{H+}}} {c_{\text{TAN}} - c_{\ce{NH3}(aq)}}.
$$

And rearrange:

$$
\frac{k_a} {c_{\ce{H+}}} \cdot (c_{\text{TAN}} - c_{\ce{NH3}(aq)}) = c_{\ce{NH3(aq)}} .
$$

A bit more, including multiplication of both sides by -1,

$$
 \frac{k_a} {c_{\ce{H+}}} \cdot c_{\ce{NH3}(aq)} + c_{\ce{NH3(aq)}} = \frac{k_a} {c_{\ce{H+}}} \cdot c_{\text{TAN}},
$$

then

$$
 \left( \frac{k_a} {c_{\ce{H+}}} + 1 \right) \cdot c_{\ce{NH3}(aq)} = \frac{k_a} {c_{\ce{H+}}} \cdot c_{\text{TAN}},
$$

and

$$
 c_{\ce{NH3}(aq)} = \frac{\frac{k_a} {c_{\ce{H+}}} \cdot c_{\text{TAN}}} {(\frac{k_a} {c_{\ce{H+}}} + 1) \cdot},
$$

which, finally, can be simplified to

$$
 c_{\ce{NH3}(aq)} = \frac{c_{\text{TAN}}} {1 + \frac {c_{\ce{H+}}} {k_a}}.
$${#eq-free-nh3-calc}

Let's implement @eq-free-nh3-calc in Python for a simple free ammonia calculator.


```{python}
"""
Description:
    A free ammonia calculator function. Does not include corrections
    for non-ideal behavior; technically only accurate for very
    dilute solutions. 
"""

import numpy as np

def free_NH3(TAN, pH, pKa = 9.56):
    """
    Calculate free ammonia concentration (NH3 (aq)) from pH and TAN concentration.

    Parameters
    ----------
    TAN : float
        Total ammoniacal nitrogen (TAN) concentration (any concentration units)
    pH : float
        Solution pH
    pKa : float
        Acid dissociation constant for NH4+

    Returns
    -------
    float with free ammonia concentration in same units as TAN input
    """

    # Calculate H+ concentration from pH
    c_H = 10**(-pH)

    # And Ka
    Ka = 10**(-pKa)

    # Apply equation from text
    c_NH3 = TAN / (1 + c_H / Ka)

    # Return solution
    return c_NH3 

```

We can test it.

```{python}
print(free_NH3(1, 9.56))
print(free_NH3(1, 7))
print(free_NH3(1, 10))
```

We see $\ce{NH4(aq)}$ is exactly half of TAN when $p\text{K}_a$ = pH, very small at pH 7, and high at pH 10, all of which are expected.




## Matrix operations

Matrices are convenient for oranizing stoichiometric coefficients and then even using in compact code for speciation calculations.
Here we will use the carbonate system as as demo.

We'll start with a stoichiometry matrix.
First we need to think about how to set it up, because at this point there are multiple routes that could be taken.
We need to select what are sometimes called "master species" or we might call "funamental species".
These species will be the reactants for all reactions.
We'll use $\ce{H2CO3^*}$ and $\ce{H+}$.
These reactants will define the columns in our stoichiometry matrix, and products will define rows.
This too is arbitrary, but seems most convenient.
If we only consider the species $\ce{H2CO3^*}$, $\ce{HCO3-}$, $\ce{CO32-}$, and of course $\ce{H+}$ and $\ce{OH-}$, our coefficient matrix is:

```{python}
#| eval: false
       | H2CO3*|  H+
       --------|----
HCO3-  |  -1   |  1
CO3-2  |  -1   |  2
  OH-  |   0   |  1
```

Although $\ce{CO32-}$ forms from $\ce{H2CO3^*}$, here our reactant is carbonic acid $\ce{H2CO3^*}$, so in this model $\ce{CO32-}$ production is expressed as two reactions combined:

$$
\ce{H2CO3^* <=> CO32- + 2H+}.
$${#eq-carb2}

So what is the use of this matrix?
We'll demonstrate after first creating the matrix in Python.

```{python}
import numpy as np

# Stoichometry matrix
#        | H2CO3*|  H+
#        --------|----
# HCO3-  |  -1   |  1
# CO3-2  |  -1   |  2
#   OH-  |   0   |  1
sc = np.array([[-1, 1],
               [-1, 2],
               [ 0, 1]])

print(sc)
```

Note that we do not get row or column names with a matrix.
So good comments (as above) are helpful.

To use the matrix, we need equilibrium constants for each reaction--so three here, one for each row.

```{python}
keq = 10**np.array([-6.3, -16.6, -14.0])
```

The first thing we can do with the matrix is to calculate reactant species concentrations once we have master species concentrations.
Look at @eq-carb2.
The relevant mass action expression is

$$
k_2 = \frac{c_{\ce{CO32-}} \cdot c_{\ce{H+}}^2}{c_{\ce{H2CO3^*}}}.
$${#eq-carb-ma2}

Rearranging gives an equation for the reactant species concentration,

$$
c_{\ce{CO32-}} = k_2 \cdot \frac{c_{\ce{H2CO3^*}}} {c_{\ce{H+}}^2}.
$${#eq-carb-ma2}

We can actually carry out this calculation using the `sc` stoichiometry matrix.

```{python}
cH2CO3s = 0.001
cHp = 1e-6
keq[1] * cH2CO3s**(-sc[1, 0]) / cHp**(sc[1, 1])
```

Do you see what we've done?
Do you understand why we included the `**(-sc[1, 0])` bit?
That makes it more general, and adaptable to the complete calculations for all reactants, which we can do using matrix operations like this:

```{python}
conc = keq * cH2CO3s**(-sc[:, 0]) / (cHp**sc[:, 1])
conc
```

This approach could work with more reactants and species with different stoichiometric coefficients.
Of course, we don't typically know master species concentrations.
When we make measurements on a water sample, create a solution in the laboratory, or simulate mass transfer and reaction of chemicals, it is the *total* concentrations that we know.
So it takes a bit more conceptual and programming trickery to come up with a general approach for solving chemical speciation problems.
In the example `carb_spec()` function below, we use two: (1) a proton balance and (2) an iterative root finder.
Take a look.

```{python}
"""
File: carb_mods.py
Authors: Sasha D. Hafner and Frederik R. Dalby
Course: Modelling 2026

Description:
    A module with carbonate speciation functions.
"""


import numpy as np
from scipy.optimize import root_scalar

def carb_spec_tot(tot):
    
    """
    Calculate pH and speciation given solute totals.

    Parameters
    ----------
    tot: ndarray or float
        total concentration of dissolved inorganic carbon (mol/kg)

    Returns
    -------
    dictionary
        concentrations of individual species (mol/kg)
    """
      
    # Set values for some constants
    # Stoichometry matrix
    #        | H2CO3*|  H+
    #        --------|----
    # HCO3-  |  -1   |  1
    # CO3-2  |  -1   |  2
    #   OH-  |   0   |  1
    sc = np.array([[-1, 1],
                   [-1, 2],
                   [ 0, 1]])
    
    # Equilibrium constant vector
    keq = 10**np.array([-6.3, -16.6, -14.0])

    # Define master species error function
    def residC(cH2CO3):
        """
        Residual of total inorganic carbon concentration
        for a given H2CO3* concentration
        """        

        # Define proton error function
        def residH(cH):
            """
            Residual of charge balance or proton condition for given 
            proton concentration cH.
            """        
            
            # Calculate concentrations of pH-dependent species
            conc = keq * cH2CO3**(-sc[:, 0]) / (cH**sc[:, 1])
            
            # Get charge balance
            return cH - np.sum(sc[:, 1] * conc)
        
        # Get H+ concentration
        cH = root_scalar(residH, bracket=[1E-14, 1], method='brentq').root

        # Species concentrations
        conc = keq * cH2CO3 * -sc[:, 0] / (cH**sc[:, 1])

        # Calculate error in total IC balance
        # Note that intermediate results cH and conc are returned here in addition to actual residual
        return tot - (cH2CO3 + np.sum(conc * -sc[:, 0])), cH, conc

    # Solve for H2CO3* concentration (mol/kg) 
    # Because residC() returns more than just residual, lambda function and indexing of result is needed
    cH2CO3 = root_scalar(lambda x: residC(x)[0], bracket=[1E-10, tot], method='brentq').root

    # Get associated cH and concentrations of all species
    resid, cH, conc = residC(cH2CO3)
    all_conc = np.concatenate(([cH2CO3, cH], conc))

    nms = ['H2CO3*', 'H+', 'HCO3-', 'CO3-2', 'OH-']
    res = dict(zip(nms, all_conc))

    # And return species concentrations (mol/kg)
    return res

```

```{python}
import carb_mods as cm

tot = 1.5E-5
concs = cm.carb_spec_tot(tot)
concs
```

We can get predicted pH:

```{python}
-np.log10(concs['H+'])
```

## Microbiology

From a modeling perspective, microbial systems are just a set of chemical reactions.
There are multiple ways microbial activity can be modelled, and selection of an aproach should depend on the objectives the model needs to meet.
An important consideration is whether active microbial biomass should be explictly included or not.
For dynamics in microbial activity related to changes in the microbial population, it must be included.
So here are some components for one approach to creating microbial models:

1. state variables: active microbial biomass, essential chemical substrates, and important products,
2. linking equations: a balanced chemical reaction that includes all state variables (stoichiometry), and
3. constitutive equation: an equation for the rate of the overall reaction (kinetics).

### Stoichiometry

Unlike simple chemical reactions such as urea hydrolysis, it isn't always possible to just look up the reaction.
But there are a few different approaches that can be used, including the microbial stoiciometry approach presented by @rittmann_environmental_2020.
@rittmann_environmental_2020 is a worthwhile read for anyone working with microbial systems.
Here we will give an introduction to the most essential parts.

Microbes (and all known life) is powered by electron transfer.
Chemotrophs harness energy from electrons transferred from reduced compounds to oxidized compounds.
For organic compounds, reduced versions contain more C and H and oxidized more O.
So these are sorted from most reduced to most oxidized: $\ce{CH4}$ (methane), $\ce{C57H104O6}$ (a lipid), $\ce{C6H12O6}$ (glucose), $\ce{CO2}$ (carbon dioxide, which provides no energy to chemotrophs).
All of these compounds except $\ce{CO2}$ could serve as electron donors for some chemotroph (technically chemoorganotroph, which is a group of chemotrophs that use reduced *organic* compounds for energy).
Of course the microorganism has to have the enzymatic machinery in place to use a particular substrate.
But as a group, microorganisms are extremely capable.

Chemotrophs need an electron acceptor too. 
These are oxidized chemicals with a strong affinity for electrons.
Common electron acceptors include $\ce{O2}$, $\ce{NO3-}$, and $\ce{SO42-}$.

Finally, fermenters do not use exactly the same approach; they do not use external electron acceptors.
Instead they essentially split a single organic compound, and transfer electrons from one product to the other.
We will work with a simple fermentation: glucose to ethanol and $\ce{CO2}$ by yeast.

Microorganisms and all life also need material to build up biomass, including numerous elements.
In modeling work and elsewhere, it is common to focus on C, H, O, and N, although others may be added depending on their importance (e.g., if S is limiting or removal in biomass is important, it can be included).
For chemoorganotrophs, the electron donor typically also serves as the source of C, H, and O.
N can come from the donor or inorganic compounds in the environment, like $\ce{NH4+}$.
H comes from the electron donor and $\ce{H2O}$, which is always available where life is active.
It is common to call the electron donor and C source the substrate.

A balanced reaction for our fermentation system is:

$$
\ce{C6H12O6 + 0.24NH4+ + 0.24HCO3- -> 
1.6CH3CH2OH + 1.84CO2 + 0.24C5H7O2N + 0.96H2O}.
$${#eq-eth-ferm}

The $\ce{C5H7O2N}$ "species" is yeast biomass, and is really an empirical chemical formula for microbial biomass.
This reaction is balanced in terms of elements and reduction-oxidation (redox). 

### Kinetics

We have looked at a first-order approach above, and while this can be a component of microbial models, it is more accurate and useful to link reaction rate to both the quantity of microbial biomass and substrate (electron donor).
A second-order approach is one option.
One common alternative is the Monod equation:

$$
r = c_{x_a} \cdot \frac{\hat{q_{max}} \cdot c_s} {c_s + k_s},
$${#eq-monod1}

where $c_{x_a} =$ active microbial biomass concentration ($\gpmc$), $\hat{q_{max}} =$ maximum substrate utilization rate, and $c_s =$ substrate concentration.


<!-- Microbial rate of growth and biomass yield.
     Monod kinetics.
     Example: CSTR. -->

## Problems

1. Formulate (pencil and paper) and implement (in Python) a simple urea hydrolysis model.
   You can assume the reaction is first-order.
   Plot predicted 

2. Create a Python function that calcuates free ammonia $\ce{NH3(aq)}$ from TAN, pH, and temperature.
   You can use this expression for the temperature dependency of Ka . . . 

3. Derive equations for calculating carbonate species concentrations from $\ce{CO2}$ partial pressure and solution pH. 
   Try to implement it in Python as a function.
   Bonus: Can you include calculation of pH instead of using it as an input?

4. Formulate and implement a model for a microbial community consuming milk processing wastewater that includes two groups: aerobic bacteria that use dissolved oxygen to oxidize the wastewater organice matter and fermentative bacteria that produce lactic acid. 
   The reactor runs in batch mode, and you do not need to include aeration; there are no inputs or outputs to the reactor.
   You can use the following empirical formula for the substrate: .
   The Microbial Stoichiometry Calculator can be used to sort out stoichiometry: https:/....
   For kinetics, use whichever approach you prefer: first-order, second-order, or Monod.
   Use your Python model to predict the effect of initial dissolved oxygen concentration on microbial populations and final lactic acid concentration.

5. A reactor . . . catalytic. . . nonlinear. . .  analytical or numerical?
