project:
  type: book
  output-dir: docs

book:
  title: "Modelling"
  author: "Sasha Hafner and Frederik Dalby"
  chapters:
    - index.qmd
    - part: "Part I: Foundations"
      chapters:
        - 01_intro.qmd
        - 02_components_formulation.qmd
        - 03_solving.qmd
    - part: "Part II: Applications"
      chapters:
        - 04_heat_transfer.qmd
        - 05_mass_transfer.qmd
        - 06_reactions_microbiology.qmd
        - 07_spatial_models.qmd
        - 08_stability.qmd
        - 09_verification_validation.qmd
        - 10_parameter_estimation.qmd
        - 11_time_variable_inputs.qmd
  appendices:
    - appendix_a_derivatives.qmd
    - appendix_b_python_style.qmd
    - appendix_c_python_types.qmd
    - appendix_d_slicing.qmd
    - appendix_e_symbols.qmd

format:
  html:
    theme: cosmo
    include-in-header:
      text: |
        <script>
        MathJax = {
          tex: {
            macros: {
              degC: "{^\\circ\\mathrm{C}}",
              Wpms: "{\\mathrm{W~m^{-2}}}",
              WpmspK: "{\\mathrm{W~m^{-2}}}",
              Jps: "{\\mathrm{J~s^{-1}}}",
              kgps: "{\\mathrm{kg~s^{-1}}}",
              kgpmc: "{\\mathrm{kg~m^{-3}}}",
              kgpmcps: "{\\mathrm{kg~m^{-3}~s^{-1}}}",
              gps: "{\\mathrm{g~s^{-1}}}"
            }
          }
        };
        </script>
execute:
  freeze: auto
