project:
  type: book
  output-dir: docs

book:
  title: "Modelling"
  author: "Sasha Hafner and Frederik Dalby"
  chapters:
    - index.qmd
    - part: "Part I: Foundations"
      chapters:
        - 01_intro.qmd
        - 02_components_formulation.qmd
        - 03_solving.qmd
    - part: "Part II: Applications"
      chapters:
        - 04_heat_transfer.qmd
        - 05_mass_transfer.qmd
        - 06_reactions_microbiology.qmd
        - 07_spatial_models.qmd
        - 08_stability.qmd
        - 09_verification_validation.qmd
#        - 10_parameter_estimation.qmd
#        - 11_time_variable_inputs.qmd
#  appendices:
#    - appx_derivatives.qmd
#    - appx_python_style.qmd
#    - appx_python_types.qmd
#    - appx_slicing.qmd
#    - appx_symbols.qmd
#    - appx_parameter_values.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    include-in-header:
      text: |
        <script>
        MathJax = {
          loader: {load: ['[tex]/mhchem']},
          tex: {
            packages: {'[+]': ['mhchem']},
            macros: {
              degC: "{^\\circ\\mathrm{C}}",
              degCpm: "{^\\circ\\mathrm{C}~m^{-1}}",
              Wpms: "{\\mathrm{W~m^{-2}}}",
              WpmspK: "{\\mathrm{W~m^{-2}~K^{-1}}}",
              WpmpK: "{\\mathrm{W~m^{-1}~K^{-1}}}",
              Jps: "{\\mathrm{J~s^{-1}}}",
              kgps: "{\\mathrm{kg~s^{-1}}}",
              kgpmc: "{\\mathrm{kg~m^{-3}}}",
              kgpmcps: "{\\mathrm{kg~m^{-3}~s^{-1}}}",
              kgpspms: "{\\mathrm{kg~s^{-1}~m^{-2}}}",
              gps: "{\\mathrm{g~s^{-1}}}",
              gpmc: "{\\mathrm{g~m^{-3}}}",
              gpmcps: "{\\mathrm{g~m^{-3}~s^{-1}}}",
              mgpl: "{\\mathrm{mg~L^{-1}}}",
              gpmol: "{\\mathrm{g~mol^{-1}}}",
              msq: "{\\mathrm{m^{2}}}",
              mps: "{\\mathrm{m~s^{-1}}}",
              msqps: "{\\mathrm{m^{2}~s^{-1}}}",
              kJpkg: "{\\mathrm{kJ~kg^{-1}}}",
              kJpkgpK: "{\\mathrm{kJ~kg^{-1}~K^{-1}}}",
              molps: "{\\mathrm{mol~s^{-1}}}",
              molpmcps: "{\\mathrm{mol~m^{-3}~s^{-1}}}",
              pers: "{\\mathrm{s^{-1}}}",
              mcbps: "{\\mathrm{m^{3}~s^{-1}}}"
            }
          }
        };
        </script>
execute:
  freeze: auto
