# Symbols
Below is a list of symbols used in the book.
It is difficult to devise a unique set of symbols across multiple fields, and despite our efforts, some are not unique and others are probably not clear.
Typical units are given for each symbol, and dimensions can be inferred from those.
Words in parentheses are not always used when we describe the terms (e.g., we may say "specific heat" or "heat transfer coefficient").

1. $A$ Cross-sectional area, typically $\text{m}^2$ 
1. $Q$ Thermal energy, typically J
1. $\dot Q$ Rate of thermal energy flow, typically $\text{J}~\text{s}^{-1} = \text{W}$
1. $q$ Heat flux, typically $\text{W}~\text{m}^{-2}$
1. $c_p$ Specific heat (capacity), typically $\text{kJ}~\text{kg}^{-1}\text{K}^{-1}$
1. $h$ (Convection) heat transfer coefficient, typically $\text{W} ~ \text{m}^{-2} ~ \text{K}^{-1}$
1. $U$ Overall heat transfer coefficient, typically $\text{W} ~ \text{m}^{-2} ~ \text{K}^{-1}$
1. $D$ Diffusivity, typically $\text{m}^2 ~ \text{s}^{-1}$
1. $k$ Thermal conductivity, typically $\text{W} ~ \text{m}^{-1} ~ \text{K}^{-1}$
1. $k_c$ (Convection) mass transfer coefficient, typically $\text{m}~\text{s}^{-1}$
1. $T$ Temperature, typically $^\circ\text{C}$ or K (equivalent for differences or derivatives)
1. $\theta$ Normalized temperature, typically $^\circ\text{C}$ or K
1. $t$ Time, typically $\text{s}$
1. $k$ First-order rate constant, typically $\text{s}^{-1}$
1. $x$ Position in 1D, typically $\text{m}$
1. $c$ Concentration of a solute, chemical species, etc., typically $\text{g} ~ \text{m}^{-3}$
1. $c$ Arbitrary constant, units vary 
1. $m$ Mass of something, typically $\text{kg}$
1. $\dot m$ Mass flow or conversion rate, typically $\text{kg}~\text{s}^{-1}$
1. $J$ Mass flux, typically $\text{kg}~\text{s}^{1}\text{m}^{-2}$
1. $n$ Molar quantity of something, $\text{mol}$
1. $\dot n$ Molar flow or conversion rate, typically $\text{mol}~\text{s}^{-1}$
1. $M$ Molar mass of some chemical (identity indicated by subscript), $\text{g}~\text{mol}^{-1}$
1. $r$ Volumetric molar flow or conversion rate, $\text{mol} ~ \text{m}^{-3} ~ \text{s}^{-1}$

