# Symbols {#sec-appx-symbols}

Below is a list of symbols used in the book.
It is difficult to devise a unique set of symbols across multiple fields, and despite our efforts, some are not unique and others are probably not clear.
Typical units are given for each symbol, and dimensions can be inferred from those.
Words in parentheses are not always used when we describe the terms (e.g., we may write "specific heat" instead of "specific heat capacity" or "heat transfer coefficient" instead of "convection heat transfer coefficient").
Note that for temperature, both K and $\degC$ show up in the table and in the rest of the book.
Kelvin is the more fundamental unit, and it is conventional to write heat transfer parameters using it.
But for all the types of heat transfer parameters we use, the two are completely interchangeable, because a temperature *difference* or *gradient* is identical in the two.
Of course, an actual temperature is not.

| Symbol | Description | Typical units |
|--------|-------------|---------------|
| $A$ | Surface or cross-sectional area | $\msq$ |
| $Q$ | Thermal energy | $\mathrm{J}$ |
| $\dot{Q}$ | Rate of thermal energy flow | $\Jps = \mathrm{W}$ |
| $q$ | Heat flux | $\Wpms$ |
| $c_p$ | Specific heat (capacity) | $\kJpkgpK$ |
| $h$ | (Convection) heat transfer coefficient | $\WpmspK$ |
| $U$ | Overall heat transfer coefficient | $\WpmspK$ |
| $k$ | Thermal conductivity | $\WpmpK$ |
| $k$ | First-order rate constant | $\pers$ |
| $k_c$ | (Convection) mass transfer coefficient | $\mps$ |
| $D$ | Diffusivity | $\msqps$ |
| $T$ | Temperature | $\degC$ or K |
| $\theta$ | Normalized temperature | $\degC$ or K |
| $t$ | Time | $\mathrm{s}$ |
| $x$ | Position in 1D | $\mathrm{m}$ |
| $c$ | Concentration of a solute, chemical species, etc. | $\gpmc$ |
| $m$ | Mass | $\mathrm{kg}$ |
| $\dot{m}$ | Mass flow or conversion rate | $\kgps$ |
| $J$ | Mass flux | $\kgpspms$ |
| $n$ | Molar quantity | $\mathrm{mol}$ |
| $\dot{n}$ | Molar flow or conversion rate | $\molps$ |
| $M$ | Molar mass (identity indicated by subscript) | $\gpmol$ |
| $r$ | Volumetric molar reaction rate | $\molpmcps$ |
| $\rho$ | Density | $\kgpmc$ |
| $\dot{V}$ | Volumetric flow rate | $\mcbps$ |

