---
title: "Modelling Compendium"
author: "Frederik and Sasha"
format: html
editor: visual
---

# Preface

This compendium is designed for the course “Modelling” in the Bachelor programmes in Biotechnology and Chemical Engineering at the Department of Biological and Chemical Engineering, Aarhus University.

Its primary aim is to introduce students to heat and mass transfer modelling through examples and case studies closely connected to real challenges in biological and chemical engineering. The compendium emphasizes both the underlying physical principles and their practical implementation.

All computational examples are implemented using Python, enabling students to develop transferable skills in scientific programming while exploring key modelling concepts.

## Chapter 1. Modelling concepts and terminology

Lumping, steady state, PDE, ODE,

## Chapter 2. Model formulation without spacial dependence

### Chapter 2.x Ficks and Fouriers law

### Chapter 2.x Newtons law of cooling and Mass transfer equation

### Chapter 2.x Conservation, governing, linking, constitutive equations

## Chapter 3. Model formulation with spacial dependence

### 3.1 From zero dimensions to one dimension

### 3.2 Governing equation and coordinate systems

Advection, diffusion, source terms. Volumetric source terms vs boundary source terms

### 3.3 Method of lines and descretization

discretize space keep derivative of time. Different schemes for discretization

### 3.4 Node and Cell based methods

illustrations of cells and nodes. what does it mean at the boundaries

### 3.5 Boundary and initial conditions

Boundary conditions dirictlet, neumann, robin... how many boundary conditions are needed, how many initial conditions are needed? Maybe move to end of this section.

#### 3.5.1 Dirichlet boundary condition

The Dirictlet BC is also referred to as a boundary condition of the first type. It describe the state variable value at the boundary. Referring to Figure x, the Dirichlet BC can be mathematically formulated as

$c(x = a, t) = \alpha(t)$,

where $a$ is at the boundary, that is $a = 0$ or $a = L$ in Figure x. The right hand side, $\alpha(t)$ implies that the value of the state variable at the boundary can depend on time, $t$, but does not have to.

**Example case**

A model that predicts how oxygen concentration changes with time and with depth of a small pond. At the top boundary (surface of the water) the concentration of oxygen is in equilibrium with the atmospheric oxygen concentration. At this boundary the value (oxygen concentration) does not change if the air is constantly exchanged, which is the case if the wind blows just mildly. This situation would be well described with a Dirichlet boundary condition. If we had put a closed chamber on top of the water, such that air could not be exchanged, then we could not do this because the concentration of oxygen in the air would decline over time as it diffuses into the water (assuming it was not saturated with oxygen already).

**Implementation in Python**

The Dirichlet BC can be enforced in many ways. Below is an example where it is enforced by setting the initial condition equal to the boundary condition. Inside the `rates()` function we initially set the derivatives at all nodes to 0 through this command `dcdt = np.zeros_line(c)`. In the `for loop` we only loop through interior nodes, because the start index is 1 (`range(1, n)`). Hence `dcdt[0]` will stay as 0 (meaning change in c is zero) and effectively ensure that the state variable value at index 0 (the boundary node) never changes from its initial value. The initial value at index 0 is set to 10 in this command after the `rates()` function: `c0[0] = 10`. Notice that the for loop stops before index n (last index), because the last argument is exclusive in the `range()` function. This means that we also have a Dirichlet boundary condition at index n, which is 0 from this command: `c0 = np.zeros(len(x_grid))`. This may not be what we want, unless something is instantly consuming oxygen at the bottom of the pond. Therefore we might have to handle the bottom boundary with a different type of boundary condition.

```{python}

# importing libraries
import numpy as np
from scipy.integrate import solve_ivp 

L = 1, # depth of pond, m 
dx = 0.01 # spatial step size, m
x_grid = np.arrange(0, 1 + dx, L) # x_grid

D = 2.0 * 10**-9 # Diffusion coefficient, m2/s

# function to describe the rate of change at every node
def rates(t, c, D, dx):
  
  n = len(c)
  dcdt = np.zeros_like(c)
  
  # interior loop from index 1 to, but excluding index n (last index)
  for i in range(1, n):
    dcdt[i] = D * (c[i-1] - 2*c[i] + c[i+1])/dx**2
  
  return dcdt

c0 = np.zeros(len(x_grid)) # initial concentration at every node (is an array)
c0[0] = 10 # at index 0 (surface of water) we change the initial concentration to the boundary condition

sol = solve_ivp(rates, t_span = [0, tmax], y0 = c0)
  
```

## Chapter 4. Model verification and validation

## Chapter 5. Parameter estimation

## Chapter 6. Model simplification and variable inputs

## Appendices
