---
---

# Beginnings
A model is a representation of a real system.
The term itself is quite general.
In this book, we will focus on models that are simplified representations of a physcial, chemical, or biological system.
Students in science and engineering might assume a model means a piece of software or code.
This can be the case, but is not the only meaning of the term "model".
A software implementation of a model, i.e., some kind of a software program or script that can be run to make model predictions, is called a *software model*.
Or, if you think of a model as a bunch of equations, that would be a *mathematical model*.
A mathematical model may exist only as a description written out on a piece of paper or printed in a book or even in someone's mind.
In this course we will work with both, as well as other types of models.

What are models used for?
For several things.
They are used to make useful predictions about the future.
For example, national policy and international agreements on greenhouse gas emissions are based rely on sophisticated "general circulation models" of the atmosphere.
These models are used to predict future climate under differnt input scenarios, including more or less greenhouse gases in the atmosphere.

In research, models are used for understanding complex systems.

And in product development, models are used for design.

*Simplification* is key to model development.
You might have an intuitive understanding that the more processes and dimensions you can cram into a model, the more accurate and in general the better it is.
That's not true.
Simplifications are what make models useful.
It is true that models should include the essential processes and components in order to be accurate and useful.
And it is also true that existing sophisticated models include many processes and components and generally increase in both complexity and accuracy over time.
So do we have a bit of a contradiction here?
Perhaps.
But even the most sophisticated model is vastly simpler than the actual physical system it represents.
And adding processes and components requires underlying math and associated parameter values.
If either is uncertain, the accuracy of the model may not improve.
Lastly, when necessary, model complexity should and usually does increase over time and as the result of contributions of multiple individuals.
That is, good modeling advice is to start simple and add more complexity if necessary.

# Types of models
There are multiple ways to group models, and the categories are useful for understanding, developing, and explaining models.

A *conceptual model* is some kind of qualitative description of a system.
It is usually helpful to include a sketch.
For example, let's say we want to develop a model to describe how the coffee in a mug cools over time.
Our conceptual model could be summarized in the sketch below.

FIGURE

In our conceptual model we assume that some quantity of heat energy is present in the coffee and mug, and that amount determines its temperature.
The rate of heat loss depends on the temperature of the coffee and mug, the ambient temperature, and some heat transfer parameter.
Our model does not explicitly include heat transfer within the coffee, or separate consideration of different routes of heat transfer, such as from the exposed coffee surface or through the wall or bottom of the mug.
A conceptual model and a sketch is a good place to start most model formulation exercises.

Formulation of a *mathematical model* is typically the objective of the following steps.

## Key terms {#sec-terms}

<!-- PDE, ODE, steady-state, lumping, conservation equations, constitutive equations,
     linking equations, governing equations, state variables, independent variables,
     model parameters, model inputs, model outputs -->


