---
title: "Modelling Compendium"
author: "Frederik and Sasha"
format: html
editor: visual
---

# Preface

This compendium is designed for the course “Modelling” in the Bachelor programmes in Biotechnology and Chemical Engineering at the Department of Biological and Chemical Engineering, Aarhus University.

Its primary aim is to introduce students to heat and mass transfer modelling through examples and case studies closely connected to real challenges in biological and chemical engineering. The compendium emphasizes both the underlying physical principles and their practical implementation.

All computational examples are implemented using Python, enabling students to develop transferable skills in scientific programming while exploring key modelling concepts.

## Chapter 1. Modelling concepts and terminology

Lumping, steady state, PDE, ODE,

## Chapter 2. Model formulation without spacial dependence

### Chapter 2.x Ficks and Fouriers law

### Chapter 2.x Newtons law of cooling and Mass transfer equation

### Chapter 2.x Conservation, governing, linking, constitutive equations

## Chapter 3. Model formulation with spacial dependence

### 3.1 From zero dimensions to one dimension

### 3.2 Governing equation and coordinate systems

Advection, diffusion, source terms. Volumetric source terms vs boundary source terms

### 3.3 Method of lines and descretization

discretize space keep derivative of time. Different schemes for discretization

### 3.4 Node and Cell based methods

illustrations of cells and nodes. what does it mean at the boundaries

### 3.5 Boundary and initial conditions

Boundary conditions (BCs) dirictlet, neumann, robin... how many boundary conditions are needed, how many initial conditions are needed? Maybe move to end of this section.

#### 3.5.1 Dirichlet boundary condition

The Dirictlet BC is also referred to as a boundary condition of the first type. It describe the state variable value at the boundary. Referring to Figure x, the Dirichlet BC can be mathematically formulated as

$c(x = a, t) = \alpha(t)$,

where $a$ is at the boundary, that is $a = 0$ or $a = L$ in Figure x. The right hand side, $\alpha(t)$ implies that the value of the state variable at the boundary can depend on time, $t$, but does not have to.

**Example case 3.5.1.1**

A model that predicts how oxygen concentration changes with time and with depth of a small pond. At the top boundary (surface of the water) the concentration of oxygen is in equilibrium with the atmospheric oxygen concentration. At this boundary the value (oxygen concentration) does not change if the air is constantly exchanged, which is the case if the wind blows just mildly. This situation would be well described with a Dirichlet BC. If we had put a closed chamber on top of the water, such that air could not be exchanged, then we could not do this because the concentration of oxygen in the air would decline over time as it diffuses into the water (assuming it was not saturated with oxygen already).

**Implementation in Python**

The Dirichlet BC can be enforced in many ways. Below is an example where it is enforced by setting the initial condition equal to the BC. Inside the `rates()` function we initially set the derivatives at all nodes to 0 through this command `dcdt = np.zeros_line(c)`. In the `for loop` we only loop through interior nodes, because the start index is 1 (`range(1, n)`) and index n (last index) is exclusive. Hence `dcdt[0]` will stay as 0 (meaning change in c over change in time is zero) and effectively ensure that the state variable value at index 0 (the boundary node) never changes from its initial value. The initial value at index 0 is set to 10 in this command after the `rates()` function: `c0[0] = 10`. Notice that the for loop stops before index n (last index), because the last argument is exclusive in the `range()` function. This means that we also have a Dirichlet BC at index n, which is 0 from this command: `c0 = np.zeros(len(x_grid))`. This may not be what we want for the model, unless something is instantly consuming oxygen at the bottom of the pond. Therefore we might have to handle the bottom boundary with a different type of BC, but for simplicity we will keep the Dirichlet BCs at both ends of the domain.

```{python}

# importing libraries
import numpy as np
from scipy.integrate import solve_ivp 

L = 1, # depth of pond, m 
dx = 0.01 # spatial step size, m
x_grid = np.arrange(0, 1 + dx, L) # x_grid

D = 2.0 * 10**-9 # Diffusion coefficient, m2/s

# function to describe the rate of change at every node
def rates(t, c, D, dx):
  
  n = len(c)
  dcdt = np.zeros_like(c)
  
  # interior loop from index 1 to index n exclusive
  for i in range(1, n):
    dcdt[i] = D * (c[i-1] - 2*c[i] + c[i+1])/dx**2
  
  return dcdt

c0 = np.zeros(len(x_grid)) # initial concentration at every node (is an array)
c0[0] = 10 # at index 0 (surface of water) we change the initial concentration to the BC

tmax = 10000 # seconds

sol = solve_ivp(rates, t_span = [0, tmax], y0 = c0, 
t_eval = np.linspace(0, tmax, 100))

plt.plot(sol.t, sol.y[-1])
plt.ylabel('O2 conc, mg/L')
plt.xlabel('Time, seconds')
  
```

If another person was to read and understand this code, we could write the Dirichlet BCs more explicitly by adding `dcdt[0] = 0` and `dcdt[-1] = 0` inside the `rates()`function just below the `dcdt = np.zeros_like(c)` line. This would not change behavior of the code, but make interpretation easier for outsiders. In more complex model code, we may unintentionally change the `dcdt` at the boundaries and in that case being explicit about the boundary conditions would help preventing that.

#### 3.5.2 Neumann boundary condition

The Neumann BC is also referred to as a boundary condition of the second type. It describes the derivative of the state variable with respect to the space variable. Thus it is closely related to the flux, with the exception that it does not specify D (the diffusion coefficient for mass transfer) or k (the conductivity for heat transfer), but only the gradient. Referring to Figure x, the Neumann BC can be mathematically formulated as:

$\frac{\partial (x = a, t)}{\partial x} = \gamma(t)$,

where $a$ is at the boundary, that is $a = 0$ or $a = L$ in Figure x. The right hand side, $\alpha(t)$ again implies that the value can depend on time, $t$, but does not have to. A very usefull and common Neumann BC would be:

$\frac{\partial (x = a, t)}{\partial x} = 0$,

When the Neumann BC is 0, it represents typically one of three cases.

1\) When the boundary is closed (mass can not get through the boundary) or insulated (heat can not flow through the boundary). This is a very common situation and would for example be a good choice for the bottom boundary in example 3.5.1.1.

2\) When we are dealing with a symmetric problem where x = 0 is a boundary e.g. in the middle of a sphere or cylinder that is symmetric around x = 0.

3\) When we have a completely open boundary, but nothing is specified about the dynamics of the state variable at the other side of the boundary. Typically there would be no description of convection or negligible convection.

**Example case 3.5.1.2**

Imagine we have a living room with a heated floor and the heat seeks upwards to the ceiling. To prevent heat loss through living room through the ceiling it is therefore build with a thick layer of polyurethane (which has a very low heat conductivity, that we will assume is 0 for the sake of this example). In this case we could assume there is no heat flux through the ceiling and set the gradient to 0. The ceiling would be the top boundary and the BC could be formulated as below

$\frac{\partial T(x=L, t)}{\partial x} = 0$

At the boundary at the floor we could have a Dirichlet BC, because the floor temperature is maintained at a constant temperature of e.g. $22^\circ C$\
$T(x = 0, t) = 22$

**Implementation in Python**

In order to implement the Neumann BC we can use a trick that involves a concept called a ghost point. Lets start with $\frac{\partial T(x=L, t)}{\partial x} = 0$ and replace the left hand side with the discretized form using finite central difference of the first derivative.

$\frac{\partial T(x=L, t)}{\partial x} = \frac{T(x_{L+1}) - T(x_{L-1})}{2dx} = 0$

Here we encounter a problem, which is $T(x_{L+1})$, because this is a point outside our model domain, since L is at the top boundary. We refer to this point as a ghost point. However, because the the LHS must be 0,

$T(x_{L+1}) = T(x_{L-1})$

In our governing equation with rectangular coordinates we have

$\rho C_p \frac{\partial T}{\partial t} = k \frac{\partial^2T}{\partial x^2} - v\frac{\partial T}{\partial x} + S$

We can eliminate the advection term (no bulk heat flow) and the source term and descretize the remaining conduction term.

$\rho C_p \frac{\partial T}{\partial t} = k \frac{T(x_{L+1}) - 2T(x_L) + T(x_{L-1})}{dx^2}$

Here we see the ghost point again, but now we can substitute it with $T(x_{L-1})$, which gets us to

$\rho C_p \frac{\partial T}{\partial t} = k \frac{2T(x_{L-1}) - 2T(x_L)}{dx^2}$

This equation effective enforces the Neumann boundary condition at the top boundary, L.

```{python}
# importing libraries
import numpy as np
from scipy.integrate import solve_ivp 

L = 2.5, # heigh of room, m 
dx = 0.01 # spatial step size, m
x_grid = np.arrange(0, 1 + dx, L) # x_grid

k = 0.026 # , J/(s * m * K)
Cp = 1006 # J/(kg * K)
rho = 1.225 # kg/m3

# function to describe the rate of change at every node
def rates(t, T, k, Cp, rho, dx):
  
  n = len(T)
  dTdt = np.zeros_like(T)
  
  # explicit showing that we have a Dirichlet BC at the bottom
  dTdt[0] = 0
  # Neumann BC at the last boundary (last index is: -1)
  dTdt[-1] = k/(Cp*rho) * (2*T[-2] - 2*T[-1])/dx**2
  
  # interior loop from index 1 to index n exclusive
  for i in range(1, n):
    dTdt[i] = k/(Cp*rho) * (T[i-1] - 2*T[i] + T[i+1])/dx**2
  
  return dTdt

T0 = np.zeros(len(x_grid)) # initial temperature of 0 at every node 
T0[0] = 22 # at index 0 (floor surface) we change the initial temperature to the BC

tmax = 10000 # seconds

sol = solve_ivp(rates, t_span = [0, tmax], y0 = T0, 
t_eval = np.linspace(0, tmax, 100))

plt.plot(sol.t, sol.y[-1])
plt.ylabel('Temp, deg C')
plt.xlabel('Time, seconds')



```

## Chapter 4. Model verification and validation

## Chapter 5. Parameter estimation

## Chapter 6. Model simplification and variable inputs

## Appendices
